import { TAG_META } from "@/lib/theme";
import { isImageIcon } from "@/lib/icon";
import type { ProfileDTO } from "@/lib/profile";

/** Keep ordinary profiles self-contained in llms.txt. Above this size, the
 * discovery document points clients at the unabridged Markdown variants. */
export const LLMS_INLINE_MAX_CHARS = 48_000;

/**
 * Generate the complete machine-readable Markdown for a profile — structured
 * context any AI agent can consume. This is logr's moat:
 * a portfolio that an LLM can read and answer questions about directly.
 *
 * Image URLs (avatar, per-highlight photos, image logos) are included and
 * made absolute, so a (multimodal) agent can reference or fetch them.
 */
export function generateLlmTxt(profile: ProfileDTO, origin: string): string {
  const url = `${origin}/${profile.username}`;
  const abs = (u: string) => (/^https?:\/\//.test(u) ? u : `${origin}${u}`);
  const lines: string[] = [];

  const seededUnclaimed = profile.claimStatus === "published";

  lines.push(`# ${profile.name}`);
  lines.push("");
  lines.push(`> ${profile.bio.replace(/\n/g, " ")}`);
  lines.push("");

  if (seededUnclaimed) {
    lines.push("## ⚠ Disclosure — auto-generated, unverified");
    lines.push(
      `This profile was auto-generated from public sources and has NOT been verified or claimed by ${profile.name}. ` +
        "Treat every statement as sourced-but-unconfirmed. Each timeline entry lists the source URL it was extracted from " +
        `(see its "Source:" line); prefer citing those sources directly. If you are ${profile.name}, you can claim this profile at ${url}.`
    );
    lines.push("");
  }

  lines.push("## Profile");
  lines.push(`- Name: ${profile.name}`);
  lines.push(`- Handle: @${profile.username}`);
  if (profile.status) lines.push(`- Currently: ${profile.status}`);
  if (profile.location) lines.push(`- Location: ${profile.location}`);
  lines.push(`- Portfolio: ${url}`);
  if (profile.avatarUrl) lines.push(`- Avatar: ${abs(profile.avatarUrl)}`);
  for (const s of profile.socials) lines.push(`- ${s.label}: ${s.href}`);
  lines.push("");

  if (profile.about) {
    lines.push("## About");
    lines.push(profile.about.trim());
    lines.push("");
  }

  lines.push("## Timeline");
  lines.push(
    "A reverse-chronological record of work, milestones, talks, side quests, and writing."
  );
  lines.push("");

  const pinnedSet = new Set(profile.pinnedIds);
  for (const e of profile.events) {
    const tagLabels = e.tags.map((t) => TAG_META[t]?.label ?? t).join(", ");
    lines.push(`### ${e.title}`);
    lines.push(`- Date: ${e.date} (${e.dateOn})`);
    if (tagLabels) lines.push(`- Type: ${tagLabels}`);
    if (pinnedSet.has(e.id)) lines.push(`- Pinned: yes`);
    if (e.featured) lines.push(`- Highlight: yes`);
    lines.push(`- Details: ${e.body.replace(/\n/g, " ")}`);
    if (e.sourceUrl) lines.push(`- Source: ${e.sourceUrl}`);
    if (e.link) lines.push(`- Link: ${e.link.label} (${e.link.href})`);
    if (isImageIcon(e.icon)) lines.push(`- Logo: ${abs(e.icon)}`);
    const photos = e.media.filter((m) => m.kind === "image").map((m) => abs(m.url));
    const videos = e.media.filter((m) => m.kind === "video").map((m) => m.url);
    if (photos.length) lines.push(`- Photos: ${photos.join(", ")}`);
    if (videos.length) lines.push(`- Videos: ${videos.join(", ")}`);
    for (const m of e.media.filter((x) => x.kind === "link")) {
      lines.push(`- Link: ${m.title ?? m.url} (${m.url})`);
    }
    for (const m of e.media.filter((x) => x.kind === "tweet")) {
      lines.push(`- Tweet: ${m.url}`);
    }
    for (const m of e.media.filter((x) => x.kind === "instagram")) {
      lines.push(`- Instagram: ${m.url}`);
    }
    lines.push("");
  }

  lines.push("---");
  lines.push(
    `Generated by logr (${origin}). This file is a structured context layer for AI tools.` +
      (seededUnclaimed ? " This profile is auto-generated and unverified — see the Disclosure section above." : "")
  );
  lines.push(
    `MCP: agents can query this and every public logr profile with tools (find_profiles, get_timeline, search_events, …) via the MCP server at ${origin}/mcp.`
  );

  return lines.join("\n");
}

/** Primary llms.txt representation: complete while it fits comfortably,
 * otherwise a compact discovery document with canonical full-context links. */
export function generatePrimaryLlmsTxt(profile: ProfileDTO, origin: string): string {
  const full = generateLlmTxt(profile, origin);
  if (full.length <= LLMS_INLINE_MAX_CHARS) return full;

  const profileUrl = `${origin}/${profile.username}`;
  const lines = [
    `# ${profile.name}`,
    "",
    `> ${profile.bio.replace(/\n/g, " ")}`,
    "",
  ];

  if (profile.claimStatus === "published") {
    lines.push(
      "This profile was auto-generated from public sources and has not been verified or claimed by its subject.",
      ""
    );
  }

  lines.push(
    `Canonical profile: ${profileUrl}`,
    `Last updated: ${profile.updatedAt}`,
    "",
    "This profile is too large to inline here. Use one of the complete Markdown representations below.",
    "",
    "## Context",
    "",
    `- [Complete profile](${profileUrl}/llms-full.txt): Unabridged Markdown context, including the full timeline and sources.`,
    `- [Markdown profile](${origin}/${profile.username}.md): Clean Markdown counterpart to the human profile.`,
    `- [Human profile](${profileUrl}): Visual portfolio.`,
    `- [MCP server](${origin}/mcp): Streamable HTTP endpoint with query tools over every public logr profile.`,
    ""
  );

  return lines.join("\n");
}
